### ISSUE TITLE
Status of this GHA

### ISSUE THREAD

**Issue by haampie** [vsoch/spack-package-action#10]
Hi @vsoch,

I'm figuring out what GitHub Actions for Spack exist and how we can better guide users to pick something that's simple and just works.

I created https://github.com/spack/setup-spack which is very basic but seems to be similar in the sense that it enables a build cache on top of GitHub Packages, using builtin OCI stuff instead of custom scripts.

I think the functionality in https://spack.readthedocs.io/en/latest/binary_caches.html#oci-docker-v2-registries-as-build-cache covers a lot of what this action is doing. The short version of it is that `spack buildcache push` can push binaries to GitHub Packages that can be `spack install`'ed next time, while at the same time making them available as container images for `docker` etc too. The gist of it is that a Spack package in the OCI build cache is the exact same blob as a container image layer.

I don't know if functionality from this GHA is not covered by the above ^ (it generates a UI for the build cache?), but if it's similar, maybe this project could refer to https://github.com/spack/setup-spack as an alternative?

**Comment by vsoch** [comment]
This action turned into this project https://github.com/syspack/pakages that uses an OCI registry for a binary cache, which (like a lot of stuff I do) was a bit ahead of it's time. I stopped actively working on it when I stepped back contributing to spack.

The one that is still active (and very useful) is the one that updates our fork for flux packages (and updates with new releases, prepares PRs, etc) https://github.com/sciworks/spack-updater.

**Comment by haampie** [comment]
Would you accept a PR that adds a link at the top of the readme to `spack/setup-spack` as a maintained alternative?

**Comment by vsoch** [comment]
This is just a personal project, why does it need to be controlled by spack?

**Comment by haampie** [comment]
Hm, it's not about "controlling" it, it's about telling users what is maintained and what is not.

But it sounds like you're not interested, so I'll close this.

**Comment by vsoch** [comment]
That’s a good point! The last commit date is a good proxy for that. Thanks.
